{{- if .Values.ollama.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-connection-info
  namespace: {{ .Values.ollama.namespace }}
data:
  # Внутренний доступ в кластере
  internal:
    host: "ollama.{{ .Values.ollama.namespace }}.svc.cluster.local"
    port: "11434"
    url: "http://ollama.{{ .Values.ollama.namespace }}.svc.cluster.local:11434"
    api_base: "http://ollama.{{ .Values.ollama.namespace }}.svc.cluster.local:11434"
  {{- if .Values.ollama.external.enabled }}
  # Внешний доступ
  external:
    host: "{{ .Values.ollama.external.host | default (printf "ollama.%s.%s" .Values.clusterName .Values.baseDomain) }}"
    port: "{{ .Values.ollama.external.port }}"
    url: "http://{{ .Values.ollama.external.host | default (printf "ollama.%s.%s" .Values.clusterName .Values.baseDomain) }}:{{ .Values.ollama.external.port }}"
    api_base: "http://{{ .Values.ollama.external.host | default (printf "ollama.%s.%s" .Values.clusterName .Values.baseDomain) }}:{{ .Values.ollama.external.port }}"
  {{- end }}
  # Конфигурация
  config:
    default_model: "{{ .Values.ollama.defaultModel }}"
    namespace: "{{ .Values.ollama.namespace }}"
    image: "{{ .Values.ollama.image }}"
  # Примеры использования
  examples: |
    # Запуск модели
    curl -X POST http://ollama.{{ .Values.ollama.namespace }}.svc.cluster.local:11434/api/generate \
      -H "Content-Type: application/json" \
      -d '{
        "model": "{{ .Values.ollama.defaultModel }}",
        "prompt": "Привет, как дела?",
        "stream": false
      }'
    
    # Список доступных моделей
    curl http://ollama.{{ .Values.ollama.namespace }}.svc.cluster.local:11434/api/tags
    
    # Скачивание новой модели
    curl -X POST http://ollama.{{ .Values.ollama.namespace }}.svc.cluster.local:11434/api/pull \
      -H "Content-Type: application/json" \
      -d '{"name": "llama3.2:3b"}'
{{- end }}
