{{- if .Values.ollama.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.ollama.namespace }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: {{ .Values.ollama.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: {{ .Values.ollama.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: {{ .Values.ollama.image }}
        ports:
        - containerPort: 11434
          name: ollama
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        - name: OLLAMA_ORIGINS
          value: "*"
        - name: OLLAMA_MODELS
          value: "/root/.ollama/models"
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama
        resources:
          {{- toYaml .Values.ollama.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: ollama-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Values.ollama.namespace }}
spec:
  selector:
    app: ollama
  ports:
  - port: 11434
    targetPort: 11434
    name: ollama
  type: ClusterIP
{{- if .Values.ollama.external.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-external
  namespace: {{ .Values.ollama.namespace }}
spec:
  selector:
    app: ollama
  ports:
  - port: {{ .Values.ollama.external.port }}
    targetPort: 11434
    name: ollama
  type: LoadBalancer
{{- end }}
{{- end }}
