{{- if .Values.ollama.enabled }}
---
# External Secret для Ollama - опциональные настройки
# Ollama обычно не требует секретов, но можно добавить для конфигурации
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ollama-vault-config
  namespace: {{ .Values.ollama.namespace }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ollama-config
    creationPolicy: Owner
  data:
  - secretKey: OLLAMA_HOST
    remoteRef:
      key: ai/ollama
      property: host
  - secretKey: OLLAMA_ORIGINS
    remoteRef:
      key: ai/ollama
      property: origins
{{- end }}
