{{- if .Values.vault.enabled }}
---
# ClusterSecretStore для подключения к Vault
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: {{ .Values.vault.address }}
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: {{ .Values.vault.tokenNamespace | default "kube-system" }}
{{- end }}
