apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-infra-gorky
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/balalaika7771/data_infra.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://192.168.1.26:6443
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

