# Конфигурация для data-infrastructure

# Имя кластера (для внутренних имен и идентификации)
clusterName: gorky

# Базовый домен для внешнего доступа
baseDomain: zhendorenko.ru

# Внешний хост (для TCP сервисов используем прямой домен, т.к. порты разные)
externalHost: zhendorenko.ru

# Vault
# ВАЖНО: Secret vault-token должен быть создан вручную:
# kubectl create secret generic vault-token -n kube-system --from-literal=token=<YOUR_TOKEN>
vault:
  enabled: true
  address: https://vault.zhendorenko.ru
  tokenNamespace: kube-system

# PostgreSQL
postgresql:
  enabled: true
  namespace: databases
  image: postgres:15
  # Внешний доступ
  external:
    enabled: true
    port: 5432
    # URL: postgres.gorky.zhendorenko.ru:5432
  # Ресурсы
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  storage:
    size: 10Gi

# Kafka
kafka:
  enabled: true
  namespace: messaging
  image: apache/kafka:3.7.0
  # Внешний доступ
  external:
    enabled: true
    port: 9092
    # URL: kafka.gorky.zhendorenko.ru:9092
  # Ресурсы
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

# MinIO
minio:
  enabled: true
  namespace: storage
  image: minio/minio:latest
  # Внешний доступ
  external:
    enabled: true
    apiPort: 9000
    consolePort: 9001
    # API URL: minio.gorky.zhendorenko.ru:9000
    # Console URL: console.minio.gorky.zhendorenko.ru
  # Ресурсы
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  storage:
    size: 50Gi

# Ollama LLM
ollama:
  enabled: true
  namespace: ai
  image: ollama/ollama:latest
  # Внешний доступ
  external:
    enabled: true
    port: 11434
    # URL: ollama.gorky.zhendorenko.ru:11434
  # Ресурсы (увеличены для работы с llama3.2:3b)
  resources:
    requests:
      memory: "3Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
  storage:
    size: 20Gi
  # Модель по умолчанию (легкая и эффективная)
  defaultModel: "llama3.2:3b"
    # Аутентификация
  auth:
    enabled: true
    username: ${OLLAMA_USER:ollama}
    password: ${OLLAMA_PASSWORD:ollama2025!SecurePass}
  # Vault интеграция для секретов
  vault:
    enabled: true
    path: "ai/ollama"
    secrets:
      - username
      - password

# Open WebUI для Ollama
openWebui:
  enabled: true
  namespace: ai
  image: ghcr.io/open-webui/open-webui:main
  # Внешний доступ
  external:
    enabled: true
    port: 8080
    # URL: open-webui.gorky.zhendorenko.ru:30880
  # Ресурсы (максимальные для стабильной работы)
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

