{{- if .Values.openWebui.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.openWebui.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: {{ .Values.openWebui.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
          name: web
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama.ai:11434"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: {{ .Values.openWebui.namespace }}
spec:
  selector:
    app: open-webui
  ports:
  - port: 8080
    targetPort: 8080
    name: web
  type: ClusterIP
{{- if .Values.openWebui.external.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-external
  namespace: {{ .Values.openWebui.namespace }}
spec:
  selector:
    app: open-webui
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30880
    name: web
  type: NodePort
{{- end }}
{{- end }}
