apiVersion: v1
kind: Service
metadata:
  name: minio-external
  namespace: storage
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30000
    name: api
  - port: 9001
    targetPort: 9001
    nodePort: 30001
    name: console
  type: NodePort
