{{- if .Values.postgresql.enabled }}
---
# ConfigMap с информацией для подключения к PostgreSQL
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-connection-info
  namespace: {{ .Values.postgresql.namespace }}
  labels:
    app: postgres
    component: connection-info
data:
  # Внутренний доступ
  internal-host: "postgres.{{ .Values.postgresql.namespace }}.svc.cluster.local"
  internal-port: "{{ .Values.postgresql.external.port }}"
  
  # Внешний доступ  
  {{- if .Values.postgresql.external.enabled }}
  external-host: "{{ .Values.externalHost }}"
  external-port: "{{ .Values.postgresql.external.port }}"
  {{- end }}
  
  # Креденшалы в postgres-credentials Secret (External Secret)
{{- end }}

