{{- if .Values.postgresql.enabled }}
---
# External Secret для PostgreSQL - автоматически синхронизируется из Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-vault-credentials
  namespace: {{ .Values.postgresql.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: databases/postgres
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: databases/postgres
      property: password
  - secretKey: POSTGRES_DB
    remoteRef:
      key: databases/postgres
      property: database
{{- end }}

