{{- if .Values.kafka.enabled }}
---
# External Secret для Kafka - автоматически синхронизируется из Vault
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-vault-credentials
  namespace: {{ .Values.kafka.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kafka-credentials
    creationPolicy: Owner
  data:
  - secretKey: KAFKA_USERNAME
    remoteRef:
      key: kafka/admin
      property: username
  - secretKey: KAFKA_PASSWORD
    remoteRef:
      key: kafka/admin
      property: password
{{- end }}

