apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: messaging
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 30092
    name: kafka
  - port: 9094
    targetPort: 9094
    nodePort: 30094
    name: kafka-external
  type: NodePort
